#pragma once
#include <unordered_map>

#define ERROR_CODE_NOT_FIND_WAVEIN_DEV			1
#define ERROR_CODE_OPEN_WAVEIN_DEV				2
#define ERROR_CODE_NOT_FIND_WAVEOUT_DEV			3
#define ERROR_CODE_OPEN_INIT_WAVEOUT_DEV		4
#define ERROR_CODE_OPEN_WAVEOUT_DEV				5

#define ERROR_CODE_START_WAVEOUT_DEV			6
#define ERROR_CODE_SET_SPEAKER_SYSTEM_VOLUME	7
#define ERROR_CODE_UNSET_PARAMETER				8

// 定義錯誤碼枚舉型態
enum class ErrorCode {
    NOT_FIND_WAVEIN_DEV = 1,
    OPEN_WAVEIN_DEV,
    NOT_FIND_WAVEOUT_DEV,
    OPEN_INIT_WAVEOUT_DEV,
    OPEN_WAVEOUT_DEV,
    START_WAVEOUT_DEV,
    SET_SPEAKER_SYSTEM_VOLUME,
    UNSET_PARAMETER
};

// 定義錯誤碼和錯誤訊息的映射
extern const std::unordered_map<ErrorCode, const wchar_t*> error_map = {
    {ErrorCode::NOT_FIND_WAVEIN_DEV, L"ERROR_CODE_NOT_FIND_WAVEIN_DEV"},
    {ErrorCode::OPEN_WAVEIN_DEV, L"ERROR_CODE_OPEN_WAVEIN_DEV"},
    {ErrorCode::NOT_FIND_WAVEOUT_DEV, L"ERROR_CODE_NOT_FIND_WAVEOUT_DEV"},
    {ErrorCode::OPEN_INIT_WAVEOUT_DEV, L"ERROR_CODE_OPEN_INIT_WAVEOUT_DEV"},
    {ErrorCode::OPEN_WAVEOUT_DEV, L"ERROR_CODE_OPEN_WAVEOUT_DEV"},
    {ErrorCode::START_WAVEOUT_DEV, L"ERROR_CODE_START_WAVEOUT_DEV"},
    {ErrorCode::SET_SPEAKER_SYSTEM_VOLUME, L"ERROR_CODE_SET_SPEAKER_SYSTEM_VOLUME"},
    {ErrorCode::UNSET_PARAMETER, L"ERROR_CODE_UNSET_PARAMETER"}
};
